# Default Dockerfile
#
# @link     https://www.hyperf.io
# @document https://hyperf.wiki
# @contact  group@hyperf.io
# @license  https://github.com/hyperf/hyperf/blob/master/LICENSE


FROM hyperf/hyperf:8.3-alpine-v3.19-swoole
LABEL maintainer="Hyperf Developers <group@hyperf.io>" version="1.0" license="MIT" app.name="Hyperf"

##
# ---------- env settings ----------
##
# --build-arg timezone=Asia/Shanghai
ARG timezone

ENV TIMEZONE=${timezone:-"Asia/Shanghai"} \
    APP_ENV=prod \
    SCAN_CACHEABLE=(false)

# update
RUN set -ex \
    # show php version and extensions
    && php -v \
    && apk update \
    && apk add --no-cache \
        postgresql-dev \
        php83-pgsql \
        php83-pecl-mongodb \
    && echo "Packages installed successfully" \
    && cd /etc/php* \
    # - config PHP
    && { \
    echo "upload_max_filesize=128M"; \
    echo "post_max_size=128M"; \
    echo "memory_limit=1G"; \
    echo "date.timezone=${TIMEZONE}"; \
    } | tee conf.d/99_overrides.ini \
    && echo "PHP configuration applied successfully" \
    # - config timezone
    && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo "${TIMEZONE}" > /etc/timezone \
    && echo "Timezone configured successfully" \
    # ---------- clear works ----------
    && rm -rf /var/cache/apk/* /tmp/* /usr/share/man \
    && php -m \
    && php --ri swoole \
    && echo -e "\033[42;37m Build Completed! :)\033[0m\n"

WORKDIR /data/project

COPY . /data/project

RUN composer install --no-dev -o

EXPOSE 9501 9502

CMD ["sh", "-c", "php bin/hyperf.php list && php bin/hyperf.php start"]